add homework for lesson#31
DerSerhii/TestDjangoProject pull request #4
Opened 2022-06-14 15:50 UTC by DerSerhii

Сначала копировал с консоли, а потом для наглядности решил все запихнуть в функции

2022-06-14 17:39 UTC, PonomaryovVladyslav requested changes
A lot of hardcodes. And You didn't have tasks to create functions for some action, only for the shell.

2022-06-14 17:39 UTC, PonomaryovVladyslav commented on blog/views.py
> +                author_id="2",
Hardcode is not allowed in 99.9% of code!!

2022-06-14 17:39 UTC, PonomaryovVladyslav commented on blog/views.py
> +                author_id="1",
Hardcode is not allowed in 99.9% of code!!

2022-06-14 17:39 UTC, PonomaryovVladyslav commented on blog/views.py
> +                author_id="2",
Hardcode is not allowed in 99.9% of code!!

2022-06-14 17:39 UTC, PonomaryovVladyslav commented on blog/views.py
> +                author_id="2",
Hardcode is not allowed in 99.9% of code!!

2022-06-14 17:39 UTC, PonomaryovVladyslav commented on blog/views.py
> +    a.save_ly()
Why did you create a special method? Why did you decide is it a more convenient?

2022-06-14 17:39 UTC, PonomaryovVladyslav commented on blog/views.py
> +    comm_lt = Comment.objects.filter(to_article__id__lt=2)
What?) lt with id?? What for?

2022-06-14 19:13 UTC, DerSerhii commented
> 

Я понимаю , что это харткодинг 100%, и что это функции-однодневки, тупые по своему содержанию до невозможности, только НЕ понимаю, как тогда выполнить первое предложение задания: "Вывести ВСЕ полученные результаты, на темплейты, каждый на отдельной странице и отдельным url-ом:"

2022-06-14 19:49 UTC, PonomaryovVladyslav commented
Вывести результат и, например, коментами оставить что ты писал в школе, как сделали другие))

2022-06-14 21:07 UTC, DerSerhii commented
> Вывести результат и, например, коментами оставить что ты писал в школе, как сделали другие))

Ну, хорошо, сделаю, все в комментах, как сделали другие)) 
только пока не понимаю, как другие, вывели на темплейт результат удаления коммента, к примеру
написать напротив номера задания - Ok?

2022-06-14 21:12 UTC, PonomaryovVladyslav commented
А какие у тебя ещё варианты?)) Ну можешь видео записать и там отображать) шутка если что

2022-06-14 21:14 UTC, DerSerhii commented on blog/views.py
> +    a.save_ly()
Чтобы оставить стандартный метод свободным, а этот использовать для частного случая

2022-06-14 21:21 UTC, DerSerhii commented
> А какие у тебя ещё варианты?)) Ну можешь видео записать и там отображать) шутка если что

Хороший вариант, я его рассматривал, обернуть save delete, чтобы он скрин делал, но мои знания ничтожно малы для этого))

2022-06-14 21:29 UTC, PonomaryovVladyslav commented
Ты дал мне забавную идею, как будет скучно, сделаю себе такой функционал))

2022-06-15 12:11 UTC, PonomaryovVladyslav requested changes
Убери хардкод, даже в коментах, ну что это такое сколько раз это повторять

2022-06-15 12:49 UTC, DerSerhii commented
> Убери хардкод, даже в коментах, ну что это такое сколько раз это повторять

Повторять достаточно и один раз))
я считал, что замечание по хардкоду относится к тому, что к функции жестко! привязаны одни и те же комменты, без вариативности,
а дело, я так понимаю, в том, что обращение по id

2022-06-16 08:17 UTC, PonomaryovVladyslav commented
> > Убери хардкод, даже в коментах, ну что это такое сколько раз это повторять
> 
> Повторять достаточно и один раз)) я считал, что замечание по хардкоду относится к тому, что к функции жестко! привязаны одни и те же комменты, без вариативности, а дело, я так понимаю, в том, что обращение по id

Нигде не должно быть никаких точных значений. Всё что можно получить, нужно сначала получить. Иначе твой код привязан к твоей базе и твоим данным, и можно поймать вообще каких угодно ошибок

2022-06-16 08:21 UTC, PonomaryovVladyslav requested changes

2022-06-16 08:21 UTC, PonomaryovVladyslav commented on blog/views.py
> +    # art_python_id = Article.objects.get(title='Python').id
title не уникальное поле, а значит, что либо нужно использовать конструкцию firter().first() или покрывать гет эксепшенами, так как иначе у тебя могут быть дупликаты и поймаешь эксепшен.

Зачем тебе поле айди? Почему не оперировать целыми объектами, в запросах ты не выиграешь, а если понадобятся данные из объектов то даже проиграешь? Это же касается всех следующих строчек тоже

2022-06-17 11:11 UTC, DerSerhii commented on blog/views.py
> +    # art_python_id = Article.objects.get(title='Python').id
Мой запрос вчера, наверное, потерялся в письмах, дублирую)

2022-06-17 11:27 UTC, PonomaryovVladyslav commented on blog/views.py
> +    # art_python_id = Article.objects.get(title='Python').id
Да, вчера нового не видел, хотя я всю почту читаю

2022-06-17 11:28 UTC, PonomaryovVladyslav requested changes

2022-06-17 11:28 UTC, PonomaryovVladyslav commented on blog/views.py
> +    # article_1 = Article.objects.get(pk=1)
Это хардкод) его быть не должно))

2022-06-17 11:28 UTC, PonomaryovVladyslav commented on blog/views.py
> +    # article = Article.objects.get(pk=1)
Ну и тут

2022-06-17 11:45 UTC, DerSerhii commented on blog/views.py
> +    # article_1 = Article.objects.get(pk=1)
Я тогда не понимаю, что такое хардкод, мы же можем знать что по pk, и что в этой созданной переменной)
могу по еще отфильтровать по title из Queryset взять конкретный по номеру инстанс и вставить его.
Если и это не туда, то не понимаю, за что борюсь и воюю с ветряными мельницами(

2022-06-17 12:02 UTC, PonomaryovVladyslav commented on blog/views.py
> +    # article_1 = Article.objects.get(pk=1)
хардкод это указание конкретных значений вместо асбтрактных, ты пишешь дай мне статью у которой pk=1, ок, а если её кто-то удалил, а если это свеже созданная база и там банально нет такого объекта?

Для решения этого вопросав текущей домашке достаточно просто в этом же коде предварительно создать объекты. Если ты их в коде создал, они точно будут, ты можешь ими пользоваться. Ну или на крайний случай использовать метод get_or_create

Да в реальности доступ по айди используется чуть больше чем везде. Но эти айди обычно получены из реальных данных. Например мы получили из базы что есть айдишки 3, 4, 8 и уже по ним обращаемся, а ты просто вписал цифру, если я склонирую себе проект, работать ничего не будет, а код который не работает в разных условиях, это плохой код. Чуть дальше мы будем рассматривать как писать тесты под фреймворк, и вот такой код не прошел бы ни один тест, потому что для тестов создаётся новая голая база, а у тебя запрос объектов по айди которых в тесте вообще не существовало бы

2022-06-18 12:07 UTC, DerSerhii commented on blog/views.py
> +    # article_1 = Article.objects.get(pk=1)
На всякий случай, дополню и этот реквест текстовым сообщением)

2022-06-18 12:10 UTC, DerSerhii commented on blog/views.py
> +    # article_1 = Article.objects.get(pk=1)
Видимо простые request a review не всегда формируют письма, почему то

2022-06-19 12:47 UTC, PonomaryovVladyslav requested changes
Зачем в 6-ом из нулл?

2022-06-19 12:47 UTC, PonomaryovVladyslav commented on blog/views.py
> +    # article_1 = Article.objects.create(title="Article 1",content="something",author=user_prof_1,time_create=timezone.now())
Обычно для таких полей как время создания используют auto now  и не переживают, но допустим

2022-06-19 12:47 UTC, PonomaryovVladyslav commented on blog/views.py
> +    # find = Comment.objects.filter(comment__isnull=True).order_by('-author__user__username', 'time_create')[:2]
А зачем там провека на из нулл?

2022-06-19 13:25 UTC, DerSerhii commented on blog/views.py
> +    # find = Comment.objects.filter(comment__isnull=True).order_by('-author__user__username', 'time_create')[:2]
Смотря куда расставлять акценты в предложении "Получить первые 2 комментария по дате создания к статье у которой имя автора последнее по алфавиту".
Если "Получить первые 2 комментария по дате создания(!) к статье у которой имя автора(!) последнее по алфавиту", то вроде как нам все равно, это какой это коммент (к статье или комменту к статье).
Если "Получить первые 2 комментария по дате создания к статье(!) у которой имя автора последнее по алфавиту", то ищем комменты именно к статье, отсекая комменты к комментам

2022-06-19 14:49 UTC, PonomaryovVladyslav commented on blog/views.py
> +    # find = Comment.objects.filter(comment__isnull=True).order_by('-author__user__username', 'time_create')[:2]
Ладно, уговорил)

2022-06-19 14:49 UTC, PonomaryovVladyslav approved these changes

2022-06-20 21:09 UTC, merged